### ISSUE TITLE
Empty List Relationships

### ISSUE THREAD

**Issue by dvanmali** [neo4j/graphql#1058]
**Describe the regression**
I'm in the progress of migrating my server to version 3.x.x and noticed that relationship types for _many-to-*_ changed. The [migration docs](https://neo4j.com/docs/graphql-manual/current/guides/v3-migration/#_many_to_relationships) mention: "[Actor] or [Actor!] will not be valid. "One-to-one" relationships such as Director remain unchanged."

I understand that [Actor] represents an invalid request since it means a null-able actor list. However **[Actor!] could be a valid syntax, an empty list of not-null Actor objects**. The current API only allows for [Actor!]!

**Last working version**

Worked up to version:
@neo4j/graphql@2.5.8

Stopped working in version:
@neo4j/graphql@3.0.0

**Type definitions**
If applicable, add your type definitions to help us reproduce the bug.

**To Reproduce**
Say you have the follower-following scenario (a similar scenario occurs in the background of my project)

```graphql
type User {
    name: String!
    followsUser: [User!] @relationship(type: "FOLLOWS", direction: OUT)
    followedBy: [User!] @relationship(type: "FOLLOWS", direction: IN)
}
```
We onboard a UserA during sign-up and create a user node (currently no followers). Later UserA decides to follow UserB (now UserA should have 1 OUT relationship and UserB should have 1 IN relationship).

Currently, this fails since we are required to write [User!]!

**Expected behavior**
Allowing [User!] allows us to set up the relationship later, not during Creation.

**Comment by dmoree** [comment]
@dvanmali Having the return type as `[User!]!` should not require a connection on creation. You should still be seeing the expected behavior. The return type has changed to say that, regardless of any followers you can expect a list.

> I understand that [Actor] represents an invalid request since it means a null-able actor list. However **[Actor!] could be a valid syntax, an empty list of not-null Actor objects**. The current API only allows for [Actor!]!

This statement I think has a misunderstanding. `[Actor!]` does not represent an "empty list of non-null `Actor` objects".  This field is saying that `null` is a valid return which I think is not something that is expected. If you want to guarantee a list, empty or not, then the return type should be non-nullable.

**Comment by dvanmali** [comment]
Appreciate the quickness and clarity in your response. I did assume the return of my query would be null instead of an empty list. I just checked with a quick creation mutation and query on my end and the response matches the empty list as you described. Thanks :)
