### ISSUE TITLE
Run query and mutations via Javascript

### ISSUE THREAD

**Issue by emorling** [neo4j/graphql#1331]
**Questions/Help**

I have read through the documentation links, and it's plain how to run queries and mutations in the playground. But I can't see a single example of how to do it via javascript?

**Comment by darrellwarde** [comment]
This isn't documented because it is nothing specific to our library, and there is a _world_ of libraries out there to do this. Apollo Client is used by many (https://www.apollographql.com/docs/react/) but really just search online for the different options and there is plenty of guidance on the next steps once your server is setup. Also feel free to join our Discord server and chat about this in the GraphQL channel: https://discord.gg/neo4j
