### ISSUE TITLE
Proposal: new validation directives

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#138]
A user in slack asked for an ability to enforce the maximum number of returned entities.

To achieve this, I would propose the following new directives:

```graphql
directive @minValue(value:Float!) on ARGUMENT_DEFINITION | FIELD_DEFINITION | INPUT_FIELD_DEFINITION
directive @maxValue(value:Float!) on ARGUMENT_DEFINITION | FIELD_DEFINITION | INPUT_FIELD_DEFINITION
```

so it can be used like this:

```graphql
type User{
  name: String
  size: Float @minValue(value: 20) @maxValue(value: 250)
}

input UserOptions {
  limit: Int @minValue(value: 0) @maxValue(value: 100)
  skip: Int @minValue(value: 0)
}
```

**Comment by TreeMan360** [comment]
I am trying to get https://www.npmjs.com/package/graphql-constraint-directive to work with this package. Is this possible?

**Comment by danstarns** [comment]
@TreeMan360 Hey! We don't directly support this. Due to the way the library works - Given some Type Definitons we produce a CURD schema with autogenerated inputs. As the inputs are auto-generated any directive you apply on the initial type is not preserved. You can however extend upon our autogenerated inputs to get this to work, you need to play around with some tools and we can sure look at making this easier but here is the gist showing how to do it: https://gist.github.com/danstarns/e3956e1633ab9866bd0172dc85470659

**Comment by darrellwarde** [comment]
This is something we'll look at (at some point), and just pointing out a couple of proposed solutions from some other issues which I will be closing as duplicates of this:

- #1550
- #1383

**Comment by corysimmons** [comment]
For clarity, dropping a comment that I'd love [Zod](https://www.npmjs.com/package/zod) support in here somehow (should probably support every big validation lib tbh).

**Comment by darrellwarde** [comment]
Given the amount of third party libraries already available for validations, we don't have the appetite to re-implement these behaviours in the library. However, we will aim to document how to use these libraries with our generated schema.
