### ISSUE TITLE
Allow defining undirected relations

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql#142]
In the [java version](https://github.com/neo4j-graphql/neo4j-graphql-java/blob/master/core/src/test/resources/issues/gh-112.adoc) the user can define undirected relations.

This feature is currently missing here.

Schema:

```graphql
type User
{
  name: String!
  uuid: ID!
  associates: [User!] @relation(name:"ASSOCIATES_WITH", direction:BOTH)
}
```

Query:

```graphql
query {
  user(uuid: $uuid) {
    uuid
    name
    associates { name uuid }
  }
}
```

Cypher:

```
MATCH (user: User)
WHERE user.uuid = $uuid
RETURN user {
    .uuid,
    .name,
    associates: [(user)-[: ASSOCIATES_WITH]-(userAssociates: User) | userAssociates {
        .name,
        .uuid
    }]
} AS user
```

**Comment by jamescottrill** [comment]
This is actually a really key feature for me. We have exactly the same functionality where a user can be friends with another user. The problem comes because users can have posts, with either public, private, friend only or friend of friend access. I'm happy for my solution below to be completely wrong and for there to be a more concise way to do this, but this is how I'm getting around this at the moment.
```js
type User {
    username: String!
    id: ID! @id
    posts: Post @relationship(type:"CREATED_BY", direction: IN)
    
}

type Post {
    id: ID! @id
    content: String!
    privacy: String!
    creator: User @relationship(type: "CREATED_BY", direction: OUT)
}
```
We want users to be able to view recent posts, so we need to be able to query the posts nodes and return all posts that the user is authorised to see. This means that we can't use the auth directive because querying all posts fails when a user isn't allowed to see all posts, so we're currently using the following:
```js
extend type User {
    friend_in: User @relationship(type:"FRIENDS_WITH", direction: IN)
    friend_out: User @relationship(type:"FRIENDS_WITH", direction: OUT)
}
extend type Post @auth(
    rules: {
        operations: [READ],
        where: {
            OR:[
                { creator: { id: "$jwt.sub" } },
                { privacy: "public" },
                { AND:[
                    { privacy: "friends" },
                    { OR:[
                      { creator: { friend_in: { user_id: "$jwt.sub"} } },
                      { creator: { friend_out: { user_id: "$jwt.sub" } } }
                        ]}
                   ]},
                   ...
            ]
        }
    }
)
```
I've excluded the friends of friends part but it's an additional OR with 4 possible options
It also adds additional complexity to writing queries, here's one to get the posts of a user's friends
```js
query{
  posts(where:{OR:[{owner:{friend_in:{user_id: "123"}}},{owner:{friend_out:{user_id: "123"}}}]}){
    id
    content 
    creator{
      username
      user_id
    }
  }
}
```
It seems unnecessarily complicated to manage when the ability to query in both directions exists. An alternative for us is to create the relationship in both directions, but that also seems to go against good practice.
If a relationship is defined as being in both directions then it seems that the assignment from one to another is arbitrary, so you could just assign it as `(in)-[:REL]->(out)`.

**Comment by morningcloud** [comment]
Is there any plan to implement this feature? My use case also makes use of undirected relationship. In Cypher it is possible to have `(n1)-[:REL]-(n2)` for undirected relationship so I see the suggestion of @Andy2003 to introduce `direction:BOTH` then this can be interpreted to cypher by not including `>` nor `<` in either side

**Comment by angrykoala** [comment]
Hi all!, [this rfc](https://github.com/neo4j/graphql/blob/dev/docs/rfcs/rfc-004-undirected-relationship-queries.md) defines the proposal for undirected relationships, which is already a work in progress for the next release. The interface is slightly different to the proposals here, but should cover the requested use cases
