### ISSUE TITLE
DB connection fails using @neo4j/graphql@3.6.0 and neo4j-driver@4.3.4 and a secure database

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#1821]
**Describe the bug**
Got an erorr "failed to find database neo4j in routing table'

**Type definitions**
Not relevant

**To Reproduce**

1. Server running @neo4j/graphql@3.6.0, neo4j-driver@4.3.4 and a database requiring the neo4j+s protocol
2. Any graphql query fails with the error outlined above

**Expected behavior**
Should connect OK

**Additional context**
Upgrading neo4j-driver fixed the issue, _but_ we were very lucky this didn't get into production (both our local database and the one in CI don't use neo4j+s), so might be worth you doing some more testing around your peerDependency on neo4j-driver (and also we shodul switch our CI database to use the same protocol as prod 😬 )

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @wheresrhys. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
This is a tricky one! By all accounts (https://neo4j.com/developer/kb/neo4j-supported-versions/), there's nothing that would stop the 4.3.4 driver working with a variety of database versions. But clearly, something wasn't compatible here.

There's not an awful lot we can do from a peer dependency standpoint, because the version we specify as a minimum should be perfectly compatible with any of the database versions we support! All in all, a bit of a weird one. Unless you have any specific suggestions?

We might consider ramping up our test matrices to test using a wide variety of driver versions perhaps...
