### ISSUE TITLE
Using @exclude directive on apollo server with ogm.neoSchema breaks apollo server

### ISSUE THREAD

**Issue by aspectgfg** [neo4j/graphql#188]
**Describe the bug**
Using any`@exclude` directives breaks apollo server when using's OGM's neoSchema vs Neo4JGraphQL's neoSchema

Type:
```graphql
type Error @exclude {
  code: String!
  message: String!
}
type ErrorResponse @exclude {
  error: Error!
}
```

Error:
```
[ERROR] 11:33:51 Error: Input Object type ErrorResponseCreateInput must define one or more fields.
```

**To Reproduce**

```ts
export const ogm = new OGM({
  typeDefs,
  driver,
  resolvers,
  config: {
    jwt: {
      secret: process.env.JWT_SECRET!,
    },
  },
});

export const neoSchema = new Neo4jGraphQL({
  typeDefs,
  driver,
  resolvers,
  config: {
    jwt: {
      secret: process.env.JWT_SECRET!,
    },
  },
});


```
Works:

```ts
const server = new ApolloServer({
  schema: neoSchema.schema
});
```

Returns Error:

```ts
const server = new ApolloServer({
  schema: ogm.neoSchema.schema
});
```

**Comment by darrellwarde** [comment]
> Returns Error:
> 
> ```ts
> const server = new ApolloServer({
>   schema: ogm.neoSchema.schema
> });
> ```

Why is it that you are using `ogm.neoSchema.schema`? This is definitely not an expected use case, and perhaps this is an export that we should remove.

The OGM is for programmatic usage which uses a GraphQL schema under the hood, so the schema it contains should not be hosted in a server.

**Comment by aspectgfg** [comment]
We’re using OGM for our custom resolvers . Why would the ogm version need a
different schema? @exclude in a typedef should still exclude CRUD even in
the OGM

**Comment by darrellwarde** [comment]
We don't think so. 🙂  You might use the `@exclude` directive to exclude CRUD because you want to implement them via custom resolvers using the OGM. So you still want the CRUD methods available through the OGM so that you can implement those custom resolvers. Your hosted schema needs to be locked down because in a lot of cases they are publicly available. The OGM schema does not need to be, because it shouldn't be hosted, so only the trusted developers of the application are using it.

I hope that's enough background on the OGM and its intentions? If so, I will close this issue as we don't see hosting the OGM's schema as an actual use case, and we will likely remove it as an export entirely in the next version.
