### ISSUE TITLE
Explicit type attribute for the @relationship directive

### ISSUE THREAD

**Issue by acmeguy** [neo4j/graphql#352]
**Is your feature request related to a problem? Please describe.**
Because of our data-model/schema complexity we are building a neo4j-type-label agnostic GraphQL schema for some parts of the model. This requires some changes in the way @neo4j/graphql handles directive.

One such case is the @relationship directive.

**Describe the solution you'd like**
I'd like to be able to explicitly supply the from and to types as attributes rather then the type names being inferred from the type names used in the graphql.schema. This would also allow us to ommit the Label as well and "get whatever is on the other end"

**Describe alternatives you've considered**
Our only obvious alternative would be to create clasess for all the Labels we have and drown the graphql schema.

**Additional context**
schema:
<pre>
type GenericType {
  shows: [GenericType] @relationship(type: "SHOWS", remote_type: "Media" direction: IN)
}
</pre>

@relationship(type: "SHOWS", remote_type: "Media" direction: IN)  (with a remote label)
@relationship(type: "SHOWS", remote_type: "" direction: IN) (without a remote label)

**Comment by darrellwarde** [comment]
We won't do this - if you want your GraphQL types to map to a different underlying label then we're going to work on some aliasing functionality. But without a GraphQL type mapped for the target end of a relationship, it would be impossible to accurately map all of the node properties to GraphQL fields.

**Comment by acmeguy** [comment]
I appreciate the dificulty this poses for mutations and was not expecting support for that.
This is - how ever - a real pain when implementing  GraphQL on top of a seasoned graph and I'd like to continue to challenge this GraphQL first approach (even though I think that it is a reasonable limitation) as it creats many limitations when dealing wiht pre-designed graphs.

Primary concern is this:
**Labels in Neo4j do not represent classes and best-practices even dictate not to treat them as such.**

You approach demands that GraphQL classes are also Neo4j classes and that labels are yous solely as class descriptors.

Please allow for enough flexibility to work around this discrepency in design priciples.

**Comment by darrellwarde** [comment]
We do have to appeal to the masses, especially at this early stage when there are lots of features to implement, and we really haven't had a lot of call for this kind of functionality.

Honestly, I just don't see it as a blocker - some people deal with GraphQL schemas with thousands of types, so adding a type for each target node label shouldn't really be a problem. If they are literally identical in fields, you could generate the types in a loop so that you technically only have to type it once and it gets produced _n_ times.

**Comment by acmeguy** [comment]
As before, I appreaciate this approach.

Adding a label is not the issue. 
The issue is that A label does not - or may not - necciserarly represent a clean class distinction or represent a class hiearacy in an accurate way.  

Since it is not encouraged by Neo4j for graphs why is it the only way for GraphQL on top of Neo4j (Excuse the stark language, I'm only trying to make a point)

**Comment by darrellwarde** [comment]
The stark language is fine, I do appreciate what you're trying to say.

We will start adding in support for features such as additional labels, so that a GraphQL type can represent many labels under the hood. However, beyond that, it is extremely difficult, without having a horrible developer experience, to un-map GraphQL type names from Neo4j labels. GraphQL is very strongly typed, and we need some way of mapping this over to Neo4j. Labels and properties are the best fit in the database for mapping over to type names and fields. 

We will be introducing support for GraphQL interfaces over relationship fields soon, which will introduce a bit of abstractness into the mix. But aside from this, unless presented with a compelling arguments and a comprehensive example of a different approach whilst maintaining a good developer experience, I don't think there's an awful lot we can do in this space.

**Comment by acmeguy** [comment]
Sounds good Darrel, thank you.

And please know that I think you guys are doing an excellent job!
