### ISSUE TITLE
Mandatory relationships when creating nodes

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#354]
**Is your feature request related to a problem? Please describe.**
It would be great to check the absence of related nodes and throw errors when creating nodes with "connect".
I see now it generates OPTIONAL MATCH for that.

Example: when you add comment to the post that doesn't exist. Now if we provide missing id:

mutation {
  createComments (input: [
   comment_id: 1
   connect: {where: {post_id: "missing node"}}
]) {id}
}

This is old unresolved issue https://github.com/neo4j-graphql/neo4j-graphql-js/issues/534

**Comment by darrellwarde** [comment]
This one is tricky, easier to enforce in some parts and very difficult in others.

The easy part is enforcing 1-1 and 1-m relationships, so if the `Comment` type is:

```graphql
type Comment {
  id: ID!
  post: Post! @relationship(type: "HAS_COMMENT", direction: IN)
}
```

We could and should enforce the non-nullability of that relationship field, which we currently don't. 🙁 

Much more difficult is when the type definition is:

```graphql
type Comment {
  id: ID!
  post: [Post!]! @relationship(type: "HAS_COMMENT", direction: IN)
}
```

Because technically, according to the data model, there is absolutely nothing wrong with a comment not having any posts! So we would need a different way of enforcement here (an argument on the directive perhaps, `minimumConnections`?!).

As such, I imagine we will address the former first, but when we do get around to it, it will be a major change where we start treating those cardinalities properly, such as not allowing 'disconnect' operations.

Sorry for no firm "yes" or "no", just wanted to fill you in on my thoughts on the matter! 😄

**Comment by Kubera2017** [comment]
Yes, at least the first 1:1 to be implemented would be great, because it's frequent case in many models, for example - Post always have User (author), Comment always have User (author) etc.

**Comment by danstarns** [comment]
Something like this would need validation inside the Cypher query using something like `apoc.util.validate`, similar to how we enforce auth, which could be used to ensure that the pattern definitely exists after connecting.

**Comment by Kubera2017** [comment]
I think current workaround is neosemantics plugin and SHACL transaction validation, you could also take a look on this for possible cases (https://neo4j.com/labs/neosemantics/4.0/validation/#_validating_transactions)

**Comment by Kubera2017** [comment]
@danstarns just checked this with such schema:
```
type Post {
        id: Int!
        has_comment: [Comment!] @relationship(type: "HAS_COMMENT", properties: "HAS_COMMENT", direction: OUT)
}

type Comment {
        id: Int!
	inverse__has_comment: Post! @relationship(type: "HAS_COMMENT", properties: "HAS_COMMENT", direction: IN)
}

interface HAS_COMMENT {
	timestamp: Int!
}
```
and got incorrect behavior:
```
mutation {
    createPosts(input: [{id: 1}]) {
        posts {
            id
        }
    }
}
```
Response:
```
Failed to invoke function 'apoc.util.validatePredicate': Caused by: java.lang.RuntimeException: @neo4j/graphql/RELATIONSHIP-REQUIREDPost.has_comment required
```

From my perspective `has_comment: [Comment!]` means that "has_comment" is not mandatory, but it will be always Comment if exists. For mandatory it should be `has_comment: [Comment!]!`

**Comment by rydamckinney** [comment]
Agreed with @kubera2017 -- the latest behavior for enforcing non-nullability appears to have caused a regression with nullable relationship fields.

`has_comment: [Comment!]`, according to the GQL schema reads that the has_comment field is nullable, but any contained objects are non-nullable.

2.5.X is treating `has_comment: [Comment!]` the same as `has_comment: [Comment!]!` which is a regression from 2.4.x behavior

**Comment by darrellwarde** [comment]
My apologies @Kubera2017 and @rydamckinney, we didn't see your comments with the issue being closed. We've just noticed this ourselves and are creating a revert commit for this now, aiming to roll out a patch release for this in 2.5.3 today.

**Comment by darrellwarde** [comment]
If you were affected by the regression introduced in 2.5.0, please upgrade to 2.5.3 where this should now be resolved! 📢
