### ISSUE TITLE
Support write-only labels

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3814]
I have a beed to put labels on types but find them regardless of whether all labels are present.

This could easily be solved with a @writeLabels directive or similar that works just like the @labels directive for is used only for writing in mutations, not for reading.

There are various reasons why this would be useful in general.

1. I'm using it to mark nodes as having an interface, but don't need this when reading and want to keep queries simple instead of checking a dozen labels.

2. It could be useful for cases where there may be old data that must still be found.

3. It may be useful when nodes should be marked as having to be post-processed asynchronously where the post-processor may drop the label again.

I have a need for (1) and (3).

**Comment by helenesanche** [comment]
Hello @jroith, thank you for raising this issue. 
This isn't on the priority radar for us, because it's advocating use of the database outside of the realm of the GraphQL library. If you customise your data outside the realm of the library it will be  hard for us to map the changes back to the API. 
While we don't advocate for this usage of the library, it would be useful if you could make an RFC providing specific use cases that will help us understand your needs better.

**Comment by jroith** [comment]
@helenesanche While this feature may be useful for existing database this is not my use case. In fact I am only creating objects through the library. However, I need to be able to put various labels on the nodes to efficiently retrieve them. In particular I put labels for the implemented interfaces. While this works, it's ugly to retrieve the objects using many labels where only the last labels is needed. There are now read-queries generated by the library that look like A:B:C:D:E:F:G:H:I:J:K:L:M:N where only N is the type interface. Basically I want A-N be written and N being used for retrieval.

**Comment by darrellwarde** [comment]
Read and write will always be the same for labels. AFAIK, the Cypher will not be slower or faster based on this, it's purely for aesthetics, and we class our generated Cypher as an internal artifact.
