### ISSUE TITLE
Constraints are probably evaluated unnecessarily

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3854]
I'm seeing a lot of validations like:

WHERE apoc.util.validatePredicate(NOT (c = 1), '@neo4j/graphql/RELATIONSHIP-REQUIRED

in queries that only update other properties. I believe it would be possible to remove those validations unless a relationship is touched that can possibly affect that property.

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @jroith. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by darrellwarde** [comment]
Hey @jroith, I believe the performance impacts here are going to be pretty minimal, and we add these checks because an update can of course contain nested operations which do affect relationships. There's quite a bit of complexity in only adding these in conditionally, and it's not something we have an appetite for right now. We're considering whether these checks should even be part of the GraphQL Library in the long run, so we don't want to invest too much time into them.
