### ISSUE TITLE
Edge max constraint on relationships

### ISSUE THREAD

**Issue by jroith** [neo4j/graphql#3899]
It would be nice to be able to set a constant max constraint on certain @relationships. My understanding is that neo4j can't really do this, but maybe it can be done by generating some validate() calls or similar?

To clarify, I would like to be able to using something like `@relationship(..., max: 2)` and then have a guarantee that no more than two connections can be made. I currently enforce this in a very roundabout way, namely by fetching the aggregation as a result and rolling back the transaction if needed. Obviously this is not nice and it only works for queries that do this, not for all possible queries.

**Comment by darrellwarde** [comment]
Whilst I can definitely see the value in this, I also think this is not a direction we want to go down right now. 

The existing 1:1 cardinality checks cause us a world of pain. I believe this is due to the fact that we're trying to build something that the database just does not support. `apoc.util.validatePredicate` also cripples performance, so we try to avoid adding new usages of it.

I'll leave this open, and perhaps at some point in the future we will get a native database constraint that we can work with.

**Comment by darrellwarde** [comment]
From now on, we're aiming to only support native database features for relationship constraints - relationship cardinality is hard to enforce!
