### ISSUE TITLE
Share request Neo4j transaction in context

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/graphql#464]
**Is your feature request related to a problem? Please describe.**
I propose you to share active transaction for custom resolvers, it will be very useful.

**Comment by darrellwarde** [comment]
The problem here is that we open and close a database session immediately before and after executing the Cypher, respectively. If we did this, we wouldn't be able to close the session, which would put the onus on the user, which is obviously a non-starter.

A more viable solution is offering a way to pass in a session in via the context which you open and close as you see fit. Precedence would be:

1. Session in context
2. Driver in context
3. Driver passed in via constructor

I believe this would work as an alternative solution for your use case?

**Comment by Kubera2017** [comment]
No, as we cannot rollback using 'session' object, main issue is 'transaction'. Basically my thought - all database queries should be executed in a single transaction (one user's request to API = one transaction). But sources of these queries during the request can be: the library query builder result, OGM usage, and this 'delegateToSchema'. The idea of 'delegateToSchema' explained more, you could check - https://graphaware.com/neo4j/2019/11/18/grandstack-tips-and-tricks.html ('Reusing generated resolvers')

**Comment by darrellwarde** [comment]
Following up here, #953 will allow for the passing in of either driver, session _or_ transaction which should allow for this to be achieved.

**Comment by Kubera2017** [comment]
Yes, exactly that I meant, thanks a lot
