### ISSUE TITLE
@auth directive for union types

### ISSUE THREAD

**Issue by mobsean** [neo4j/graphql#545]
**Describe the bug**
Trying to use the @auth directive with union throws error in schema validation.

**Type definitions**
This, as stated in the docs, works:

```gql
type Drill {
    id: ID
    name: String
}
type Mill {
    id: ID
    name: String
    cuttingEdges: Int
}

extend type Drill @auth(rules: [{ isAuthenticated: true }])
extend type Mill @auth(rules: [{ isAuthenticated: true }])
```

But does not scale when I need to add more types and I want to query for all types.

**To Reproduce**
Using Union:
```
type Drill{
    id: ID
    name: String
}
type Mill {
    id: ID
    name: String
    cuttingEdges: Int
}

union Tool = Drill | Mill

extend union Tool @auth(rules: [{ isAuthenticated: true }])
```

But when I try to use the @auth directive to extend a union I get:

```
Error: Unknown directive "@auth".
    at assertValidSDLExtension
```

**Expected behavior**
@auth directive should be applied to the union type.

**System:**

-   OS: Windows
-   Version: @neo4j/graphql@2.3.0
-   Node.js version: 16.6.1

**Comment by darrellwarde** [comment]
An update on this - it's likely that we're _not_ going to allow `@auth` to be applied to union types. Let me explain why.

Let's start with interfaces - an interface defines a common behaviour for several types, and if you apply the `@auth` directive to an interface type, the rules will get picked up by any type that implements it. I believe that an interface should have been used in place of the union in this use case. Additionally, if an implementing type has its own `@auth` directive, these rules override the base rules. 

A union, however, gives no guarantee of similarity between types. It allows you to combine together any number of arbitrary types into one, so it would feel odd to give all of those completely arbitrary types the same `@auth` rules. Additionally, due to unions being defined after the fact of types; what would we do in the case of both the type and the union having an `@auth` directive? Precedence is unclear.

For all of these reasons, we feel this is a bad idea, so our advice will be to either leverage an interface, or apply the rules to each individual type.

**Comment by mobsean** [comment]
thank you for this detailed explanation. Meanwhile I applied the rules to each type separately.
