### ISSUE TITLE
@auth directive: rules dont apply when using 'where'

### ISSUE THREAD

**Issue by mobsean** [neo4j/graphql#636]
**Describe the bug**
@auth does not apply when searching with 'where:'. It`s possible to run queries without authentification.

**Type definitions**
```
type Something {
  id: ID! @id
  name: String!
}
extend type Something @auth( rules: [ { isAuthenticated: true } ] )
```

This also happens when using different rules arrays. with or with operations array and so on.

**To Reproduce**
run query with where argument

```
query{
  somethings(where: { name: "foo" }) {
    id
    name
  }
}
```

**Expected behavior**
Get an error: "unauthenticated".

Instead I get an empty array. Which is the search result in this case.

Only if the query find something in the database I get the expected error.

**System (please complete the following information):**

-   OS: Windows and Linux
-   Version: @neo4j/graphql@2.5.0
-   Node.js version: 16.6.1

**Comment by mobsean** [comment]
I just realized, when there is no "Something" node in the database, the query will also return an empty array instead of an error "unauthenticated".

**Comment by darrellwarde** [comment]
> I just realized, when there is no "Something" node in the database, the query will also return an empty array instead of an error "unauthenticated".
> 
> ```
> query{
>   somethings {
>     id
>     name
>   }
> }
> ```
> 
> will return
> 
> ```
> {
>   "data": {
>     "somethings": []
>   }
> }
> ```

So this is a known thing, originally highlighted in #195, but we don't see it as a massive issue. It's just due to the fact that the auth rules are applied as Cypher clauses, which don't run if zero nodes are returned from a Cypher `MATCH`.

Which leads me onto the bug reported here. It's actually the exact same issue but as a result of the `MATCH` plus auth `WHERE` resulting in zero nodes, and the actual auth Cypher clause not being reached. Thoughts on whether this ups the severity of the problem originally reported in #195 @danstarns @angrykoala?

**Comment by mobsean** [comment]
That´s how I found this. Running my tests agains an empty DB in CI.

I mean, technically it´s an information that maybe should not leak into public. 

You can run unauthenticated searches against the APi and know that there is not a result/node in the database.

I´ll close this issue, since #195 still open.
