### ISSUE TITLE
Allow schemas to predefine temporal scalars

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#659]
**Is your feature request related to a problem? Please describe.**
Just migrating from neo4j-graphql-js. We build our fairly large schema using graphql-compose, which expects the entire schema to be consistent (except for directives), hence it expects `Date`, `DateTime` etc to be defined. I need to strip these out prior to augmentation by @neo4j/graphql or I get the following error:

```
"DateTime" already exists in the schema. It cannot also be defined in this type definition.

Type "Date" already exists in the schema. It cannot also be defined in this type definition.

Type "Time" already exists in the schema. It cannot also be defined in this type definition.
```
**Describe the solution you'd like**
Be forgiving about the pre-existence of these scalars when augmenting the schema

**Comment by darrellwarde** [comment]
Hey @wheresrhys, when you say you have your own scalars here, I'm assuming they are scalars used in fields which don't persist to the database?

It's very hard for us to be forgiving here, because without our scalars, serializing/parsing in/out of database datetime formats just won't work.

I'd be interested to hear how you think we could implement "forgiveness" here.

**Comment by wheresrhys** [comment]
I'm not sure I explained the problem very well. It's a catch-22

Option 1 - We define the scalars
graphql-compose successfully builds a consistent schema which we can then pass in to Neo4jgraphQL. At this point we get an error saying the scalars already exist but shouldn't

Option 2 - We don't define the scalars
graphql-compose fails to generate the schema with errors such as `Date is not defined`

We do not use the scalars for any fields that are not 'owned' by Neo4jGraphQL.

The only implementation we have in the schema passed to Neo4jGraphQL is:

```
scalar Date
scalar DateTime
scalar Time
```

I suppose by 'forgiving' I mean that if those definitions exist but appear to not have any other behaviour implemented, then Neo4jGraphQL should just take ownership of those names.

**Comment by darrellwarde** [comment]
Riiiiight, now I understand, thanks for re-explaining.

This is a tricky one for us! When we didn't have schema validation in place, users were constantly passing in these definitions (as well as definitions for types such as `Point`) and then reporting that these types weren't working. So much so that it was possibly our second most reported bug. So adding in this validation step has made the library a lot more friendly to users. 

Tell me, what function do you use in `graphql-compose` to get your schema? We use `toSDL()` and I've just had a look and noticed there is an `omitScalars` option:

```ts
const typeDefs = composer.toSDL({ omitScalars: true });
```

Whichever function you use, you might find that there is an option which allows you to not output the scalar definitions you added.

**Comment by wheresrhys** [comment]
I don't see that option anywhere in the 9.0.4 docs, source or types, or for the underlying graphql library it wraps. Bit confused as AFAIK you're on the same version (9.0.4). And when you say 'we use' do you mean within the library or in other projects, as I don't see `omitScalars` in the @neo4j/graphql source either.

**Comment by darrellwarde** [comment]
Sorry if that wasn't clear. When I say we use, the `toSDL()` function is what we use to get our type definitions out of our `graphql-compose` instance: https://github.com/neo4j/graphql/blob/master/packages/graphql/src/schema/make-augmented-schema.ts#L968

Digging into that function in the `graphql-compose` source, you can find it at https://github.com/graphql-compose/graphql-compose/blob/master/src/SchemaComposer.ts#L997 and see that it has options object `SchemaComposerPrinterOptions`

If you follow that through, you see that is composed of `Options` and `SchemaFilterTypes`: https://github.com/graphql-compose/graphql-compose/blob/master/src/utils/schemaPrinter.ts#L97

In the `Options` object finally, you can see `omitScalars`, which if it does what it says on the tin, should not print out the scalars when outputting the type definitions, so should work with our validation! https://github.com/graphql-compose/graphql-compose/blob/master/src/utils/schemaPrinter.ts#L71

**Comment by wheresrhys** [comment]
Thanks - I was following a similar thread but backed out as my IDE search wasn't finding the string so i thought I was probably looking in the wrong place. I think the search settings I have might need a tweak
