### ISSUE TITLE
Feature request: a `cypher` method, a bit like the `@cypher` directive through the OGM

### ISSUE THREAD

**Issue by maieulChevalier** [neo4j/graphql#716]
**Is your feature request related to a problem? Please describe.**

It's not possible to write more complex cypher queries using the OGM. 

**Describe the solution you'd like**

For example:

```javascript
const User = ogm.model("User");
const users = await User.cypher({ 
  query: `            
    MATCH (u:User)
    RETURN u
  `
});
```
So basically the `cypher` method could have the following arguments: `query`, `selectionSet`, `args`, `context` and `rootValue`, allowing us to use it like the `@cypher` directive. And just like the `@cypher` directive, "[When returning an object type, all fields of the type must be available in the Cypher return value](https://neo4j.com/docs/graphql-manual/current/type-definitions/cypher/#_object_types)".

**Additional context**

This feature would also be a nice workaround to #692, allowing us to add custom logic inside our resolvers for queries and mutations that currently use the @cypher directive.

```javascript
const User = ogm.model("User");
const resolvers = {
  Query: {
    currentUser: async (_source, args, context, info) => {
      console.log("I can add custom logic, Hooray!")
      const users = await User.cypher({ 
        query: `            
          MATCH (u:User)
          RETURN u
        `
      });
      return users;
    },
  }
});
```
It would just not be a great dev experience for those wanting to add custom logic on top of auto-generated queries like `createUsers` or `deleteUsers`, since they would have to rewrite their queries and mutations with the OGM syntax inside their resolvers.

**Comment by darrellwarde** [comment]
Maybe I'm missing something here, but what is the difference between this and just using a driver instance in your custom resolver and querying the database directly?

**Comment by maieulChevalier** [comment]
By "using a driver instance in your custom resolver and querying the database directly", do you mean using something like the following syntax inside a custom resolver?

``` javascript
let query = `
  MATCH (u:User)
  RETURN u
`; 
const posts = await context.driver.session().run(query).then(response => response.records.map(record => record.get('u').properties));
```

If that's it, the difference for me is that this cypher query will just return the User node and it's properties. I can't access data from the selection set specified by the graphql query unless I rewrite the cypher return statement to match the selection set. 

It's not very flexible since the graphql query selection set might change and I'm not even sure I would be able to write such a return statement :smile:. This seems especially difficult and long to do when there are custom @cypher directives on properties since I would have to rewrite the @cypher directives statements inside the resolver's cypher return statement.

I know that the OGM's selection set must be defined manually currently but it's still much easier (just a matter of copy & paste). And I understand from [this](https://github.com/neo4j/graphql/pull/52#pullrequestreview-580103355) that it should be set at "selection time" in the future.

**Comment by danstarns** [comment]
This is cool because it would also allow you to use `selectionSet`: 

```js
const users = await User.cypher({
    query: `            
      MATCH (u:User)
      RETURN u
    `,
    selectionSet: `
        {
            name
            posts {
                title
                comments {
                    comment
                }
            }
        }
    `,
});
```

**Comment by maieulChevalier** [comment]
> This is cool because it could also allow you to use `selectionSet`

Exactly :ok_hand: Thanks for the clear example :)

Still, I think that #692 would be useful since using the OGM inside custom resolvers would still be a bit rigid. Same problem as above, the graphql query might change, and so the devs would have to adapt the OGM query accordingly every time in different custom resolvers. But it would be good anyways to have the cypher method with the OGM since it can be used outside of resolvers.

**Comment by maieulChevalier** [comment]
I wanted to give a try at making a PR for this but unfortunately I don't really know typescript, nor do I know how to test on such a library.. But in case it helps, I think that the logic for a cypher method should be similar to the [`cypherResolver` function](https://github.com/neo4j/graphql/blob/master/packages/graphql/src/schema/resolvers/cypher.ts). Maybe the resolve function within it could be extracted and reused in both the cypher method and the `cypherResolver` function.

**Comment by lewisparma** [comment]
This issue and [#692 ](https://github.com/neo4j/graphql/issues/692) are also blocking us from migrating from neo4j-graphql-js.
We have a complex data model, since we keep track of all the changes done the objects in our model. Our DB structure looks similar to this: https://medium.com/neo4j/keeping-track-of-graph-changes-using-temporal-versioning-3b0f854536fa .
 
This means that today we have our own custom neo4j procedures for creating/updating/deleting objects and we don’t use auto-generated ones. Our mutations are calling custom procedures we defined in neo4j directly.

Here is an example of one of our mutations definitions today inside the schema.

`UpdateArea(name: String!, changeID: String!, settings: _AreaUpdateInput!): [Area!]! @cypher(statement: "MATCH (e: Area {name: $name}) with e CALL versioner.crud.patch(e, $changeID, $settings.dbData.labels,$settings.dbData.stateProps,$settings.dbData.oneToOneRels,$settings.dbData.oneToManyRels,$settings.dbData.selectors,$settings.dbData.dynamicEntitiesRels) YIELD node RETURN node")`

Our customer resolver needs to parse the _AreaUpdateInput object and create the dbData structure that it's be passed to the custom generic neo4j proceudure. We still rely on neo4j-graphql-js library to handle querying back the selection set specified in the request.(so changing the cypher query to get the right data back)

**Comment by benjamin-rood** [comment]
re: selectionSet, you do know you can extract that from the GraphQL request at runtime, right? You don't HAVE to have it hardcoded.

**Comment by lewisparma** [comment]
yes, the functionality we look for is to update the base cypher query to return data that matches the runtime selectionset, as the old library did.

**Comment by dmoree** [comment]
I attempted to implement this method. There were two approaches. Perhaps @darrellwarde or @danstarns could comment on either approach.

#### Approach 1: Reimplement a modified `cypherResolver` from `@neo4j/graphql`
Implementation: https://github.com/dmoree/graphql/commit/01135a31eb96e6aff3a910b71505fc82d5d99a8b

As you can see this relies heavily on internal implementations in both `graphql-js` and `@neo4j/graphql`. Since `createProjectionAndParams` takes a `resolveTree` it is important to have an `info` object in which to parse. One could pass the `info` argument from the resolver, but in order to pass a custom selection set one would have to construct this. My approach seems quite hacky. I don't see this as particularly feasible.

#### Approach 2: Extend `Neo4jGraphQL`
Implementation: https://github.com/dmoree/graphql/commit/cada48f2bdf9cd5a20ad676585af05eb8f796e5a

An additional method [`mergeSchema`](https://github.com/neo4j/graphql/commit/1746b3bd7fb58dc8a27977ca1db2d5e5c3140f8c) could be added to the class in order to extend the schema. Then one could add a custom `Query` field in order to have access to the resolvers. It would be as if it was written at the time of instantiation. The implementation is cleaner, but I'm not sure extending the schema every time the `cypher` method is called is a good idea. Perhaps one could from within the method create a hash of the cypher statement and append it to the query name and check to see if the generated query field already exists in the schema and only if it doesn't is `mergeSchema` called. In that case, any subsequent calls of `.cypher` would bypass the need to add the custom query to the existing schema. Overall, this seems like a much better approach than the first.


Perhaps these approaches are wrong and there exists a simpler one, but I found this to be not a trivial feature to implement.

**Comment by maieulChevalier** [comment]
Hey @dmoree, thank you for trying to implement this. We had a bit of a discussion with darrell on discord yesterday and it seems to me now that [`graphql-middleware`](https://github.com/neo4j/graphql/issues/692#issuecomment-1017481261) is probably the best approach to add custom logic on top of generated resolvers (even those generated by the @cypher directive).

I think it might be best to talk about the usefulness of this `cypher` method first, and then think about how it should work. 

### Usefulness

As of the current library, I can see two use cases :

- inside a REST `POST` or `GET` request.
- Or inside a `graphql-middleware`. But right now using a driver session is enough for me for side effects since I don't need the selectionSet.

Another completely different approach could be to completely replace the @cypher directive altogether, but this would mean reinventing the wheel with a lot of work and breaking changes for not much added value I guess.

### Implementation

> #### Approach 1: Reimplement a modified `cypherResolver` from `@neo4j/graphql`
> Implementation: [dmoree@01135a3](https://github.com/dmoree/graphql/commit/01135a31eb96e6aff3a910b71505fc82d5d99a8b)

This is kind of what I was thinking about doing at first. While it seems to be extremely powerful, it has no schema validation whatsoever, which can lead to more errors in large code bases. It seems that the @cypher directive works better. Please tell me if I'm wrong.

> #### Approach 2: Extend `Neo4jGraphQL`
> Implementation: [dmoree@cada48f](https://github.com/dmoree/graphql/commit/cada48f2bdf9cd5a20ad676585af05eb8f796e5a)

This is interesting, but again, why not just use the @cypher directive?

I'm thinking perhaps that a better approach would be to just call a graphql function that would run already generated @cypher resolvers (just like the other `find`, `create`, `update`, or `delete` methods). It could be expressed like this instead:

``` graphql
  type Query {
    currentUser(id: ID!): User!
      @cypher ( 
          statement:
            """
              MATCH (u:User{id:$id})
              RETURN u
            """
          )
  }
```

``` javascript
const user = await User.query({
    field: "currentUser"
    selectionSet: `
        {
            name
            posts {
                title
                comments {
                    comment
                }
            }
        }
    `,
});
```

Or even 

``` javascript
const user = await User.currentUser({
    selectionSet: `
        {
            name
            posts {
                title
                comments {
                    comment
                }
            }
        }
    `,
});
```
Though I don't know if it's possible to dynamically create methods based on the schema.

**Comment by darrellwarde** [comment]
@dmoree, personally I don't believe that either of these approaches are appropriate here and both feel a bit "hacky".

Both of these approaches kind of break the OGM paradigm which is that it's just a wrapper around the Neo4j GraphQL Library schema. Once we start doing things like this, lines get blurred and the OGM becomes something that it was never intended to be.

The only addition I would like to see to the OGM is the ability to call custom Cypher fields in the root `Query` and `Mutation` types and get back the results as OGM model instances. This is functionality that is missing at present, and would fit into the OGM feature set quite nicely.

If you want a custom Cypher field in your schema to only be available to the OGM, then we should make sure that it can be marked as `@private` and then you can have private OGM custom Cypher.

This issue was mainly borne out of the need to wrap resolvers with custom logic, but this has now been resolved in #692 where it has been pointed out that `graphql-middleware` can be used for this. Part of me says with that in mind, this feature is no longer required for the time being. 

I have raised issue #843 which I believe is perhaps a more appropriate solution here - I would appreciate thoughts.

**Comment by darrellwarde** [comment]
> > #### Approach 2: Extend `Neo4jGraphQL`
> > Implementation: [dmoree@cada48f](https://github.com/dmoree/graphql/commit/cada48f2bdf9cd5a20ad676585af05eb8f796e5a)
> 
> This is interesting, but again, why not just use the @cypher directive?
> 
> I'm thinking perhaps that a better approach would be to just call a graphql function that would run already generated @cypher resolvers (just like the other `find`, `create`, `update`, or `delete` methods). It could be expressed like this instead:
> 
> ```graphql
>   type Query {
>     currentUser(id: ID!): User!
>       @cypher ( 
>           statement:
>             """
>               MATCH (u:User{id:$id})
>               RETURN u
>             """
>           )
>   }
> ```
> 
> ```js
> const user = await User.query({
>     field: "currentUser"
>     selectionSet: `
>         {
>             name
>             posts {
>                 title
>                 comments {
>                     comment
>                 }
>             }
>         }
>     `,
> });
> ```
> 
> Or even
> 
> ```js
> const user = await User.currentUser({
>     selectionSet: `
>         {
>             name
>             posts {
>                 title
>                 comments {
>                     comment
>                 }
>             }
>         }
>     `,
> });
> ```
> 
> Though I don't know if it's possible to dynamically create methods based on the schema.

This is more akin to my solutions proposed in #843, just with a slightly different twist!

**Comment by darrellwarde** [comment]
What I'm going to do is close this one for now in favour of #843, where we can have a more focussed conversation on how to expose custom Cypher fields in the `Query` and `Mutation` root types. I think that's the first step towards a solution here - if users have more customisation requirements beyond that, then we can revisit this another time!

**Comment by dmoree** [comment]
@darrellwarde 
I think this feature request may have been convoluted by the underlying issue motivating it. My understanding is that given an arbitrary cypher `statement`, query the database and return those fields in the `selectionSet` at the point of invocation. The idea is that one would not know what this statement would be at the point of instantiation in order to use the `@cypher` directive directly in the `typeDefs` given to the constructor. Plainly, if you have a `User` model in an `OGM`, take a cypher statement that returns `:User` nodes from the database and project the requested fields (or map those) in the given `selectionSet`. 

#843 seems to be something different in that you're simply trying to execute an already existing cypher statement within the `typeDefs` used in instantiating the `OGM`. If the only purpose is to use it in field resolvers, then perhaps it would make more sense to take this approach. However, if `@neo4j/graphql-ogm` were to stand on its own I think this seems like a reasonable feature, i.e. executing arbitrary cypher statements against the database. But again, it appears to be non-trivial so if there isn't much need it probably shouldn't have much urgency.

> This is interesting, but again, why not just use the @cypher directive?

That would not allow for arbitrary cypher statements. If one were simply looking for:

> I'm thinking perhaps that a better approach would be to just call a graphql function that would run already generated @cypher resolvers (just like the other `find`, `create`, `update`, or `delete` methods). It could be expressed like this instead:
> 
> ```graphql
>   type Query {
>     currentUser(id: ID!): User!
>       @cypher ( 
>           statement:
>             """
>               MATCH (u:User{id:$id})
>               RETURN u
>             """
>           )
>   }
> ```
> 
>  ```js
> const user = await User.query({
>     field: "currentUser"
>     selectionSet: `
>         {
>             name
>             posts {
>                 title
>                 comments {
>                     comment
>                 }
>             }
>         }
>     `,
> });
> ```

I don't want to speak too quickly, but I'm sure this wouldn't be too difficult.

Even making a dynamic method:



> Or even
> 
> ```js
> const user = await User.currentUser({
>     selectionSet: `
>         {
>             name
>             posts {
>                 title
>                 comments {
>                     comment
>                 }
>             }
>         }
>     `,
> });
> ```

Would work exactly the same, albeit with more Typescript problems perhaps. Maybe the type generation of the `OGM` could fix this I'm not sure.

**Comment by dmoree** [comment]
An attempt at `Model.query` here: https://github.com/dmoree/graphql/commit/1a478e9f63c5547f9d216891826481e91e6dbd93

Test here: https://github.com/dmoree/graphql/commit/334795d9b4d23de5d2949d7d053a2d81c67ab89d

**Comment by maieulChevalier** [comment]
> But again, it appears to be non-trivial so if there isn't much need it probably shouldn't have much urgency.

Yeah, seems like a lot of work for not much added value.

> The idea is that one would not know what this statement would be at the point of instantiation in order to use the `@cypher` directive directly in the `typeDefs` given to the constructor.

Maybe a concrete example would help understand if there are situations where this would be useful.

**Comment by maieulChevalier** [comment]
Just want to share [this from OWASP](https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#injection-prevention) for precaution in case this idea gets another shot in the future. Maybe a powerful cypher method would be prone to attacks since the cypher statement wouldn't be sanitized / could be anything.

**Comment by maieulChevalier** [comment]
Just want to share [this from OWASP](https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#injection-prevention) for precaution in case this idea gets another shot in the future. Maybe a powerful cypher method would be prone to attacks since the cypher statement wouldn't be sanitized / could be anything.
