### ISSUE TITLE
Clarify long term support for past major versions

### ISSUE THREAD

**Issue by wheresrhys** [neo4j/graphql#995]
One great thing about the new project is that it is properly supported.

However, noting that the upcoming v3.0.0 release drops support for the relatively recent neo4j 4.1. and graphql 15, I wonder if you have a policy on patching older versions of the library because if a vulnerability is found it may not be possible/easy for users to upgrade to your latest major version because of being tied to older versions of neo4j or graphql.

It'd be very reassuring if you could publish a clear timeline of how long you commit to keeping old versions ​patched for vulnerabilities ​or other serious flaws.

**Comment by darrellwarde** [comment]
Basically, for Neo4j support, we're precisely following the supported versions list: https://neo4j.com/developer/kb/neo4j-supported-versions/

Note that 3.5 was never supported in this library, but following that, we will always support what is on that list.

As far as our current policy, we don't keep old versions patched at all - once 3.0.0 comes out, 2.x will no longer get patched. That is our current policy, based on the fact that we haven't really had calls for otherwise, so we would have to have a real shout out from customers if we were to change this.

Sorry for the slightly wishy washy answer!

**Comment by wheresrhys** [comment]
Thanks for the reply. I do slightly worry that we might get caught out by changes in the API design in future forcing us to upgrade our entire stack, but I guess the upfront design decisions, and leaning in to the established graphql connect pattern, does the lend the API some stability. I also really like that in v3 you've deprecated rather than removed some filter behaviours, which definitely makes keeping up with the core GRANDstack toolset easier.
